name: CI Pipeline

on: [push, pull_request] # Triggers on pushes or pull requests to any branch

jobs:
  build: # Name of the job
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
      - uses: actions/checkout@v4 # Action to clone the repo to the runner
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
